---
engines:
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
plugins:
  eslint:
    enabled: true
    config:
      config: ./.eslintrc
    checks:
      complexity:
        enabled: false
