language: node_js
node_js:
  - "node"
  - "stable"
  - "11"
  - "10"
  - "9"
  - "8"

stages:
  - lint
  - test
  - coverage

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: coverage
      script: npm run coverage
