language: node_js
node_js:
  - "stable"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4.2"
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
