language: node_js
os: linux
dist: bionic
cache: npm
node_js:
  - node
  - lts/*
  - stable
  - 13
  - 12
  - 11
  - 10
  - 9
  - 8

stages:
  - lint
  - test
  - coverage

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: coverage
      script: npm run coverage
